
[build]
  command = "npm install --prefix outfit-generator && npm run build --prefix outfit-generator"
  publish = "outfit-generator/dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev --prefix outfit-generator"
  targetPort = 5173
  publish = "outfit-generator/dist"